### ISSUE TITLE
Support for IE9

### ISSUE THREAD

**Issue by therollingtester** [SymbioSweden/careers#1]
It would be great to have support for IE9 and up. If it's not possible, we should at least have an Alert/Infobox to inform the end user that it is time to update their browser.

![screen shot 2016-01-14 at 16 01 43](https://cloud.githubusercontent.com/assets/3662539/12327768/87331556-bad8-11e5-8123-bd4b54feceac.png)

**Comment by johnie** [comment]
@therollingtester Problem solved! [http://www.theverge.com/2015/3/17/8230631/microsoft-is-killing-off-the-internet-explorer-brand](http://www.theverge.com/2015/3/17/8230631/microsoft-is-killing-off-the-internet-explorer-brand)

**Comment by therollingtester** [comment]
True! Could we then add the alert saying "We do not support ancient browsers"?
